import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { Chart } from '../components/Chart/Chart'
import { ISpeakerChartRow, IWordChartRow } from '../interfaces/interface'

// fetch api/hello.ts
const getBySpeakerId = async (speakerId: number) => {
  const res = await fetch('/api/speaker', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ 
      speakerId: speakerId 
    }),
  })

  const data = await res.json()
  return data
}

const getByWord = async (word: string) => {
  const res = await fetch('/api/word', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      word: word
    }),
  })

  const data = await res.json()
  return data
}

const Home: NextPage = () => {
  const [item, setItem] = React.useState<any>(null)
  const [wordItem, setWordItem] = React.useState<any>(null)
  const [speakerId, setSpeakerId] = React.useState<number>(1)
  const [word, setWord] = React.useState<string>('')

  React.useEffect(() => {
    getBySpeakerId(speakerId).then((data: {data: ISpeakerChartRow[]}) => {
      setItem(data.data)
    })
  }, [speakerId])

  React.useEffect(() => {
    getByWord(word).then((data: {data: IWordChartRow[]}) => {
      setWordItem(data.data)
    })
  }, [word])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        {/* Line with valuepairs */}

        <input type="number" value={speakerId} onChange={(event) => setSpeakerId(+event.target.value)} />
        <input type="text" name="test" placeholder={word} id="wordInput" />
        <button onClick={() => {
          setWord((document.getElementById("wordInput") as HTMLInputElement).value)
        }}>Click</button>


        <div style={{ width: "80vw", height: "80vh" }}>
          <Chart speakerData={item} />
        </div>
        <div style={{ width: "80vw", height: "80vh" }}>
          <Chart wordData={wordItem} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
